{#Main}
---
title: "Rapport de performances"
author: "Elouan"
date: "{$date}"
output:
  html_document:
    theme: spacelab
  pdf_document: default
---

```{r, echo=FALSE} 
library('reshape2')
library('ggplot2')
```

{#}

{#Data}
```{r, echo=FALSE} 
# ---- DATA -----
data = read.csv(file="monitor.csv",head=TRUE,sep=";")
```
{#}

{#Cpu}

#### Performances processeur

```{r, echo=FALSE} 
# ---- CPU -----

cpu = read.csv(file="cpu.csv",head=TRUE,sep=";")

initialTimestamp <- cpu[1, "time"]
time = cpu[["time"]] - initialTimestamp

cols = c("usr.all",
         "nice.all",
         "sys.all",
         "iowait.all",
         "irq.all",
         "soft.all",
         "steal.all",
         "guest.all",
         "gnice.all")
            
cpuAll = data.frame(time, cpu[,cols])
cpuAll = melt(cpuAll, id.vars="time")

ggplot(cpuAll, aes(time, value)) + geom_line(aes(colour=variable))

```
{#}

{#Ram}

#### Mémoire vive et mémoire d'échange utilisée

```{r, echo=FALSE} 

# ---- RAM -----

# Compute timestamp --
initialTimestamp <- data[1, "time"]
time = data[["time"]] - initialTimestamp

# Choose columns --
cols = c("ram.total","ram.free", "swap.total", "swap.free")
ram = data.frame(time, data[,cols])

# Compute Ram and Swap used --
ramUsed = (ram[["ram.total"]] - ram[["ram.free"]]) / 1000
swapUsed = (ram[["swap.total"]] - ram[["swap.free"]]) / 1000
max = (ram[1, "ram.total"] + ram[1, "swap.total"]) / 1000
min = 0
ramGraph = data.frame(time, ramUsed, swapUsed)

# Display -- 
ramGraph = melt(ramGraph, id.vars="time")
ggplot(ramGraph, aes(time, value, fill=variable)) + 
  geom_line(aes(colour=variable)) +
  ylim(c(min, max)) + 
  geom_area(position = 'stack')

```
{#}

{#Diskspace}

#### Espace disque utilisé

```{r, echo=FALSE} 

# ---- DISKSPACE -----

# Compute timestamp --
initialTimestamp <- data[1, "time"]
time = data[["time"]] - initialTimestamp

# Choose columns --
cols = c("diskspace.total..","diskspace.used..", "diskspace.free..")
diskspace = data.frame(data[,cols])

# Compute Diskspace used --
diskspace = diskspace / 1000000
max = diskspace[1, "diskspace.total.."]
min = 0
diskspaceGraph = data.frame(time, diskspace[["diskspace.used.."]])

# Display -- 
diskspaceGraph = melt(diskspaceGraph, id.vars="time")
ggplot(diskspaceGraph, aes(time, value, fill=variable)) + 
  geom_line(aes(colour=variable)) +
  ylim(c(min, max)) + 
  geom_area(position = 'stack')

```
{#}


{#Diskio}

#### Lecture/écriture

```{r, echo=FALSE} 
# ---- Diskio -----

diskio = read.csv(file="diskio.csv",head=TRUE,sep=";")

initialTimestamp <- diskio[1, "time"]
time = diskio[["time"]] - initialTimestamp

cols = c("read",
         "write")
            
diskioGraph = data.frame(time, diskio[,cols])
diskioGraph = diskioGraph / 1000000

diskioGraph = melt(diskioGraph, id.vars="time")

ggplot(diskioGraph, aes(time, value)) + geom_line(aes(colour=variable))

```
{#}